### ISSUE TITLE
Unable to add an account on mastodon.social as friend

### ISSUE THREAD

**Issue by gbraad** [akirk/friends#138]
When trying to add a mastodon.social account, eg. gbraad@mastodon.social the plugin errors out.
Other remote servers work, such as pixelfed, friendica, etc. Perhaps there is a block in place?

**Comment by akirk** [comment]
Hm, I was successfully able to follow the account, I get a `Sent follow request with response: 202 Accepted`. Do you have a specific error message? On which page is it displayed?

**Comment by gbraad** [comment]
I tried this from https://social.gbraad.nl as a test. IS there anything I can do to debug the issue?

**Comment by akirk** [comment]
An specific error message or screenshot would be helpful!

**Comment by gbraad** [comment]
Unfortunately the standard settings only show:

![image](https://user-images.githubusercontent.com/1894/209810779-07e30a20-ce10-4865-9313-dffe811ccfd6.png)

so have to check if something got recorded in a log file.

**Comment by akirk** [comment]
Did you receive an e-mail from your WordPress install? Maybe it landed in the spam.

**Comment by gbraad** [comment]
It did not send an email. But I think the error.log recorded it:
```
[Wed Dec 28 05:01:23.244044 2022] [fcgid:warn] [pid 409527:tid 3643094746880] [client 38.32.68.195:9776] mod_fcgid: stderr: PHP Fatal error:  Uncaught TypeError: array_merge(): Argument #2 must be of type array, WP_Error given in /home/spotsnel_host2/sites-gbraad/gbraad.nl/blog/wp-content/plugins/friends/includes/class-feed.php:881, referer: https://blog.gbraad.nl/wp-admin/admin.php?page=add-friend
[Wed Dec 28 05:01:23.244108 2022] [fcgid:warn] [pid 409527:tid 3643094746880] [client 38.32.68.195:9776] mod_fcgid: stderr: Stack trace:, referer: https://blog.gbraad.nl/wp-admin/admin.php?page=add-friend
[Wed Dec 28 05:01:23.244124 2022] [fcgid:warn] [pid 409527:tid 3643094746880] [client 38.32.68.195:9776] mod_fcgid: stderr: #0 /home/spotsnel_host2/sites-gbraad/gbraad.nl/blog/wp-content/plugins/friends/includes/class-feed.php(881): array_merge(Array, Object(WP_Error)), referer: https://blog.gbraad.nl/wp-admin/admin.php?page=add-friend
[Wed Dec 28 05:01:23.244139 2022] [fcgid:warn] [pid 409527:tid 3643094746880] [client 38.32.68.195:9776] mod_fcgid: stderr: #1 /home/spotsnel_host2/sites-gbraad/gbraad.nl/blog/wp-content/plugins/friends/includes/class-admin.php(1580): Friends\\Feed->discover_available_feeds('https://mastodo...'), referer: https://blog.gbraad.nl/wp-admin/admin.php?page=add-friend
[Wed Dec 28 05:01:23.244157 2022] [fcgid:warn] [pid 409527:tid 3643094746880] [client 38.32.68.195:9776] mod_fcgid: stderr: #2 /home/spotsnel_host2/sites-gbraad/gbraad.nl/blog/wp-content/plugins/friends/includes/class-admin.php(1781): Friends\\Admin->process_admin_add_friend(Array), referer: https://blog.gbraad.nl/wp-admin/admin.php?page=add-friend
[Wed Dec 28 05:01:23.244173 2022] [fcgid:warn] [pid 409527:tid 3643094746880] [client 38.32.68.195:9776] mod_fcgid: stderr: #3 /home/spotsnel_host2/sites-gbraad/gbraad.nl/blog/wp-includes/class-wp-hook.php(308): Friends\\Admin->render_admin_add_friend(''), referer: https://blog.gbraad.nl/wp-admin/admin.php?page=add-friend
[Wed Dec 28 05:01:23.244188 2022] [fcgid:warn] [pid 409527:tid 3643094746880] [client 38.32.68.195:9776] mod_fcgid: stderr: #4 /home/spotsnel_host2/sites-gbraad/gbraad.nl/blog/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array), referer: https://blog.gbraad.nl/wp-admin/admin.php?page=add-friend
[Wed Dec 28 05:01:23.244202 2022] [fcgid:warn] [pid 409527:tid 3643094746880] [client 38.32.68.195:9776] mod_fcgid: stderr: #5 /home/spotsnel_host2/sites-gbraad/gbraad.nl/blog/wp-includes/plugin.php(517): WP_Hook->do_action(Array), referer: https://blog.gbraad.nl/wp-admin/admin.php?page=add-friend
[Wed Dec 28 05:01:23.244216 2022] [fcgid:warn] [pid 409527:tid 3643094746880] [client 38.32.68.195:9776] mod_fcgid: stderr: #6 /home/spotsnel_host2/sites-gbraad/gbraad.nl/blog/wp-admin/admin.php(259): do_action('friends_page_ad...'), referer: https://blog.gbraad.nl/wp-admin/admin.php?page=add-friend
[Wed Dec 28 05:01:23.244241 2022] [fcgid:warn] [pid 409527:tid 3643094746880] [client 38.32.68.195:9776] mod_fcgid: stderr: #7 {main}, referer: https://blog.gbraad.nl/wp-admin/admin.php?page=add-friend
[Wed Dec 28 05:01:23.244575 2022] [fcgid:warn] [pid 409527:tid 3643094746880] [client 38.32.68.195:9776] mod_fcgid: stderr:   thrown in /home/spotsnel_host2/sites-gbraad/gbraad.nl/blog/wp-content/plugins/friends/includes/class-feed.php on line 881, referer: https://blog.gbraad.nl/wp-admin/admin.php?page=add-friend
```

```
[Wed Dec 28 05:02:34.540363 2022] [fcgid:warn] [pid 409527:tid 3643094746880] [client 38.32.68.195:32098] mod_fcgid: stderr: PHP Fatal error:  Uncaught TypeError: array_merge(): Argument #2 must be of type array, WP_Error given in /home/spotsnel_host2/sites-gbraad/gbraad.nl/blog/wp-content/plugins/friends/includes/class-feed.php:881, referer: https://blog.gbraad.nl/wp-admin/admin.php?page=add-friend
[Wed Dec 28 05:02:34.540439 2022] [fcgid:warn] [pid 409527:tid 3643094746880] [client 38.32.68.195:32098] mod_fcgid: stderr: Stack trace:, referer: https://blog.gbraad.nl/wp-admin/admin.php?page=add-friend
[Wed Dec 28 05:02:34.540455 2022] [fcgid:warn] [pid 409527:tid 3643094746880] [client 38.32.68.195:32098] mod_fcgid: stderr: #0 /home/spotsnel_host2/sites-gbraad/gbraad.nl/blog/wp-content/plugins/friends/includes/class-feed.php(881): array_merge(Array, Object(WP_Error)), referer: https://blog.gbraad.nl/wp-admin/admin.php?page=add-friend
[Wed Dec 28 05:02:34.540471 2022] [fcgid:warn] [pid 409527:tid 3643094746880] [client 38.32.68.195:32098] mod_fcgid: stderr: #1 /home/spotsnel_host2/sites-gbraad/gbraad.nl/blog/wp-content/plugins/friends/includes/class-admin.php(1580): Friends\\Feed->discover_available_feeds('https://mastodo...'), referer: https://blog.gbraad.nl/wp-admin/admin.php?page=add-friend
[Wed Dec 28 05:02:34.540486 2022] [fcgid:warn] [pid 409527:tid 3643094746880] [client 38.32.68.195:32098] mod_fcgid: stderr: #2 /home/spotsnel_host2/sites-gbraad/gbraad.nl/blog/wp-content/plugins/friends/includes/class-admin.php(1781): Friends\\Admin->process_admin_add_friend(Array), referer: https://blog.gbraad.nl/wp-admin/admin.php?page=add-friend
[Wed Dec 28 05:02:34.540502 2022] [fcgid:warn] [pid 409527:tid 3643094746880] [client 38.32.68.195:32098] mod_fcgid: stderr: #3 /home/spotsnel_host2/sites-gbraad/gbraad.nl/blog/wp-includes/class-wp-hook.php(308): Friends\\Admin->render_admin_add_friend(''), referer: https://blog.gbraad.nl/wp-admin/admin.php?page=add-friend
[Wed Dec 28 05:02:34.540516 2022] [fcgid:warn] [pid 409527:tid 3643094746880] [client 38.32.68.195:32098] mod_fcgid: stderr: #4 /home/spotsnel_host2/sites-gbraad/gbraad.nl/blog/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array), referer: https://blog.gbraad.nl/wp-admin/admin.php?page=add-friend
[Wed Dec 28 05:02:34.540540 2022] [fcgid:warn] [pid 409527:tid 3643094746880] [client 38.32.68.195:32098] mod_fcgid: stderr: #5 /home/spotsnel_host2/sites-gbraad/gbraad.nl/blog/wp-includes/plugin.php(517): WP_Hook->do_action(Array), referer: https://blog.gbraad.nl/wp-admin/admin.php?page=add-friend
[Wed Dec 28 05:02:34.540559 2022] [fcgid:warn] [pid 409527:tid 3643094746880] [client 38.32.68.195:32098] mod_fcgid: stderr: #6 /home/spotsnel_host2/sites-gbraad/gbraad.nl/blog/wp-admin/admin.php(259): do_action('friends_page_ad...'), referer: https://blog.gbraad.nl/wp-admin/admin.php?page=add-friend
[Wed Dec 28 05:02:34.540585 2022] [fcgid:warn] [pid 409527:tid 3643094746880] [client 38.32.68.195:32098] mod_fcgid: stderr: #7 {main}, referer: https://blog.gbraad.nl/wp-admin/admin.php?page=add-friend
[Wed Dec 28 05:02:34.540629 2022] [fcgid:warn] [pid 409527:tid 3643094746880] [client 38.32.68.195:32098] mod_fcgid: stderr:   thrown in /home/spotsnel_host2/sites-gbraad/gbraad.nl/blog/wp-content/plugins/friends/includes/class-feed.php on line 881, referer: https://blog.gbraad.nl/wp-admin/admin.php?page=add-friend
```

**Comment by akirk** [comment]
Thank you, this is helpful indeed. I fixed the bug in d2d3445. Likely there was an error while retrieving details about the ActivityPub account and maybe this error has been cached so worth trying again even without this bugfix. Sorry for the trouble!

**Comment by gbraad** [comment]
will try.

**Comment by akirk** [comment]
Thank you for confirming!
